<a href="https://colab.research.google.com/github/SharonneKemboi/Numpy-Data-Science/blob/master/Sharon_NumPy_Bootcamp_Graded_Hands_on_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

###Task 1:   

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.



In [ ]:
#Import Numpy
import numpy as np  

#random numpy array that rep an image
original = np.random.random((3,28,28))

#array flat that converts to 1 x(3x28x28) use reshape
flat = original.reshape(1,3*28*28)

#covert to 1D array and use flat.flatten method to flatten array
one_arr = flat.flatten()

#Print shape of all arrays
print (original.shape) 
print (flat.shape)
print (one_arr.shape)

(3, 28, 28)
(1, 2352)
(2352,)


### Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




In [ ]:
#Print Dimension of the arrays
print (original.ndim)
print (flat.ndim)
print (one_arr.ndim)

#Print Memory address of the arrays
print (id(original))
print (id(flat))
print (id(one_arr))

#Print shape of the arrays
print (original.shape)
print (flat.shape)
print (one_arr.shape)

#Print data types of the arrays
print (original.dtype)
print (flat.dtype)
print (one_arr.dtype)

3
2
1
139966147954320
139966148197520
139966147464912
(3, 28, 28)
(1, 2352)
(2352,)
float64
float64
float64


### Task 3: 
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [ ]:
#arraywhich is negative of original 
negative_original = np.negative(original)

#Print the new array
print(negative_original)

#Add the original and new arrays
sum_of_arrays = original + negative_original

# Print the result
print(sum_of_arrays)

[[[-0.29303211 -0.73537027 -0.01180026 ... -0.94220108 -0.85572365
   -0.76160226]
  [-0.18871859 -0.64366664 -0.4212331  ... -0.49012104 -0.41478399
   -0.55893864]
  [-0.89853894 -0.29534689 -0.35095842 ... -0.05764117 -0.10188815
   -0.84406624]
  ...
  [-0.68056969 -0.21837747 -0.26392981 ... -0.18121472 -0.82154297
   -0.15043887]
  [-0.2050387  -0.9291305  -0.08841377 ... -0.21798658 -0.52395173
   -0.74475571]
  [-0.64897455 -0.7548463  -0.69023787 ... -0.95368557 -0.18315389
   -0.5119431 ]]

 [[-0.01887119 -0.41588779 -0.53761715 ... -0.59306547 -0.66693895
   -0.01195258]
  [-0.51688969 -0.98135612 -0.77026686 ... -0.79129604 -0.2503266
   -0.54724587]
  [-0.30638588 -0.21653332 -0.67227197 ... -0.36672672 -0.85980781
   -0.09129433]
  ...
  [-0.02982917 -0.30738224 -0.05065225 ... -0.3543585  -0.36957109
   -0.66890098]
  [-0.02275614 -0.90950944 -0.81571842 ... -0.37805977 -0.93078643
   -0.7154787 ]
  [-0.88594889 -0.4013393  -0.66505971 ... -0.09648665 -0.84936006
   -0.9

###Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [ ]:
#Accesing the first 10 elements of the 2nd rowof the second matrix
second_rmatrix = original[1][1][0:9]
# Print the result
print(second_rmatrix)


[0.51688969 0.98135612 0.77026686 0.02797024 0.25998196 0.4476374
 0.47678376 0.73813604 0.14744243]


### Task 5 (Optional)
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [ ]:
a = original[2][0:3]

# Print the shape of the Blue pixel matrix
print(a.shape) 
#Print the first 3 rows.
print(a[:])


(3, 28)
[[0.57916278 0.03094958 0.7433478  0.93921343 0.66675125 0.56624947
  0.92216463 0.43305095 0.93130046 0.5930364  0.40059997 0.50824278
  0.79534109 0.35685661 0.92302408 0.34695553 0.05063595 0.89698573
  0.03679052 0.1207883  0.88256452 0.76153896 0.43910035 0.28307151
  0.7796936  0.0098119  0.79163372 0.76283574]
 [0.9135515  0.2119895  0.40956322 0.35792769 0.73966896 0.14400822
  0.97720892 0.590501   0.17794851 0.24917398 0.51426775 0.82293213
  0.73331432 0.10631393 0.36253333 0.77282141 0.41617211 0.52103482
  0.15616803 0.91547477 0.3298421  0.20604363 0.60428445 0.70144617
  0.752904   0.15606132 0.31842852 0.83023379]
 [0.63543278 0.34196176 0.09649975 0.50387879 0.86726429 0.09434976
  0.74809928 0.46009414 0.67623217 0.03787115 0.32471164 0.67181996
  0.01899754 0.66865682 0.61495612 0.30932787 0.97859169 0.61113551
  0.86791361 0.92495233 0.8380228  0.43138962 0.85689102 0.00780408
  0.75462381 0.97505193 0.78027942 0.89005713]]


### Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [ ]:
#1 dimensional numpy array of the first 50 even numbers - Use arange method
first_fifty_even = np.arange(0, ((2 * 50) - 1), 2)

#Converting to a 10x5 numpy array using reshape method
reshape_fifty = first_fifty_even.reshape(10, 5)

# print its transpose
print(reshape_fifty.transpose())

[[ 0 10 20 30 40 50 60 70 80 90]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 8 18 28 38 48 58 68 78 88 98]]


###Task 7 
Consider the 10x5 array created in Task 6. Find the mean of each row and column. You may use in built functions or write your own code.

In [ ]:
  #Mean of column 
mean_of_column = reshape_fifty.mean(axis=0)
print (mean_of_column)     


[45. 47. 49. 51. 53.]


In [ ]:
  #Mean of row
mean_of_row = reshape_fifty.mean(axis=1)
print (mean_of_row)      

[ 4. 14. 24. 34. 44. 54. 64. 74. 84. 94.]


### Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

No, we cannot create a 3x3 array of the first 50 even numbers.

Because, there is no way the dimensions 3x3 can accommodate exactly 50 elements, since 50 is not divisible by 3

The array shape or its rows and columns should multiply and give the answer equal to the number of required elements. 
For 50 elements, the allowed mxn dimensions are 2x25,5x10,10x5,25x2. 